# Generated by Django 3.2.9 on 2025-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('danceability', models.FloatField(default=0.0)),
                ('energy', models.FloatField(default=0.0)),
                ('key', models.IntegerField(default=0)),
                ('loudness', models.FloatField(default=0.0)),
                ('mode', models.IntegerField(default=1)),
                ('acousticness', models.FloatField(default=0.0)),
                ('instrumentalness', models.FloatField(default=0.0)),
                ('liveness', models.FloatField(default=0.0)),
                ('valence', models.FloatField(default=0.0)),
                ('tempo', models.FloatField(default=120.0)),
                ('duration_ms', models.IntegerField(default=180000)),
                ('time_signature', models.IntegerField(default=4)),
                ('num_bars', models.IntegerField(default=0)),
                ('num_sections', models.IntegerField(default=0)),
                ('num_segments', models.IntegerField(default=0)),
                ('classification', models.IntegerField(default=0)),
            ],
        ),
    ]
