# Generated by Django 3.2.9 on 2025-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='star_rating',
            field=models.IntegerField(default=3),
        ),
    ]
